# Site settings
title: malt3
email: malte@maltepoll.de
description: > # this means to ignore newlines until "baseurl:"
  Ich bin ein Informatikstudent aus Deutschland und interessiere mich für IT Sicherheit, hacken und Netzwerke.
  Außerdem ❤ ich Open Source.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://malt3.de" # the base hostname & protocol for your site
twitter_username: malt3
github_username:  malt3

# Build settings
markdown: kramdown


# Outputting
permalink:	/:year/:month/:day/:title/
